
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package ejemplo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PYCOMA = 12;
  public static final int MENOR = 11;
  public static final int INT = 19;
  public static final int IGUAL = 9;
  public static final int MENORIGUAL = 4;
  public static final int MASNUM = 7;
  public static final int PARIZQ = 14;
  public static final int PARDER = 15;
  public static final int ID = 20;
  public static final int MENOSUNO = 6;
  public static final int LLAVEIZQ = 16;
  public static final int COMA = 13;
  public static final int LLAVEDER = 17;
  public static final int MAYOR = 10;
  public static final int EOF = 0;
  public static final int DIFERENTE = 2;
  public static final int MASUNO = 8;
  public static final int MAYORIGUAL = 3;
  public static final int NUMERO = 21;
  public static final int error = 1;
  public static final int FOR = 18;
  public static final int MENOSNUM = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DIFERENTE",
  "MAYORIGUAL",
  "MENORIGUAL",
  "MENOSNUM",
  "MENOSUNO",
  "MASNUM",
  "MASUNO",
  "IGUAL",
  "MAYOR",
  "MENOR",
  "PYCOMA",
  "COMA",
  "PARIZQ",
  "PARDER",
  "LLAVEIZQ",
  "LLAVEDER",
  "FOR",
  "INT",
  "ID",
  "NUMERO"
  };
}

